// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using swaggerapi.Data;

#nullable disable

namespace swaggerapi.Migrations
{
    [DbContext(typeof(TrainContext))]
    [Migration("20230422122513_train")]
    partial class train
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0-preview.3.23174.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("swaggerapi.Models.Train", b =>
                {
                    b.Property<int>("trainId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("trainId"));

                    b.Property<string>("from")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("to")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("trainName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("trainId");

                    b.ToTable("Train");

                    b.HasData(
                        new
                        {
                            trainId = 12131,
                            from = "Pune",
                            to = "Mumbai",
                            trainName = "Vande Bharat"
                        },
                        new
                        {
                            trainId = 12132,
                            from = "Mumbai",
                            to = "Pune",
                            trainName = "Vande Bharat"
                        },
                        new
                        {
                            trainId = 12732,
                            from = "Delhi",
                            to = "Jalandhar",
                            trainName = "Sarbat Da Bhala"
                        },
                        new
                        {
                            trainId = 12535,
                            from = "Uk",
                            to = "Delhi",
                            trainName = "Kathgodam Express"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
